// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDji2JI7TsHbT9KatNKIFz6eNss8dn1oew',
    appId: '1:743889624098:web:2d93c55ac41daf62eebe7b',
    messagingSenderId: '743889624098',
    projectId: 'e-commerce-aaddd',
    authDomain: 'e-commerce-aaddd.firebaseapp.com',
    storageBucket: 'e-commerce-aaddd.firebasestorage.app',
    measurementId: 'G-8H6Y6RQVJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlHVoisGdZ-aeU-sdek520hQVNVlXows',
    appId: '1:743889624098:android:d036efab37cb8d61eebe7b',
    messagingSenderId: '743889624098',
    projectId: 'e-commerce-aaddd',
    storageBucket: 'e-commerce-aaddd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Kx_c98RvASuXUNhHaf09apr4uB6fFgY',
    appId: '1:743889624098:ios:ddb5ded546a67309eebe7b',
    messagingSenderId: '743889624098',
    projectId: 'e-commerce-aaddd',
    storageBucket: 'e-commerce-aaddd.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Kx_c98RvASuXUNhHaf09apr4uB6fFgY',
    appId: '1:743889624098:ios:ddb5ded546a67309eebe7b',
    messagingSenderId: '743889624098',
    projectId: 'e-commerce-aaddd',
    storageBucket: 'e-commerce-aaddd.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
